baseurl = "https://kenlyau.com/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "KenLyau"
theme = "kken"
paginate = 50
googleAnalytics = "UA-155730944-1"

[author]
  name = "ken"
  email = "newallah@gmail.com"
[taxonomies]
  tag = "tags"
  category = "categories"
[params]
  beian = "蜀ICP备17001479号-2"
  copyright = "武侯区岭尚智计算机信息技术咨询服务部"
