name: push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.0'
        # extended: true

    - name: Build
      run: hugo -D
    
    - name: Setup Ossutil
      uses: manyuanrong/setup-ossutil@v1.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        # 填写Bucket所在地域的域名信息，可参考访问域名和数据中心。
        endpoint: "oss-cn-chengdu.aliyuncs.com"
        # AccessKeyID
        access-key-id: ${{ secrets.AccessKeyID }}
        # AccessKeySceret
        access-key-secret: ${{ secrets.AccessKeySceret }}
    
    - name: Deploy
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: ossutil cp public oss://ken-blog/ -rf
